// 公开评论数据 - 2026年4月 (Trustpilot + Reddit)
// 生成时间: 2026-04-21
// 数据来源: Trustpilot (60条) + Reddit (45条)
const PUBLIC_REVIEWS_APR = [
  {
    "id": "TP-001",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "NL",
    "rating": "5",
    "sentiment": "正面",
    "category": "其他",
    "issue_type": "待确认",
    "original": "I really am very happy with bambulab.",
    "chinese": "[Trustpilot/NL] I really am very happy with bambulab."
  },
  {
    "id": "TP-002",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "CA",
    "rating": "5",
    "sentiment": "正面",
    "category": "商城服务",
    "issue_type": "下单流程",
    "original": "All the items in my order came in promptly with no damage",
    "chinese": "[Trustpilot/CA] All the items in my order came in promptly with no damage"
  },
  {
    "id": "TP-003",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "US",
    "rating": "5",
    "sentiment": "正面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Grandson gift. My 11 year old grandson asked for a special birthday gift. The Bambu lab A1 made everything easy. We assembled in no time and had our first print done shortly thereafter.",
    "chinese": "[Trustpilot/US] Grandson gift. My 11 year old grandson asked for a special birthday gift. The Ba..."
  },
  {
    "id": "TP-004",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "GB",
    "rating": "5",
    "sentiment": "正面",
    "category": "其他",
    "issue_type": "待确认",
    "original": "easy to navigate, confirm selection and pay.",
    "chinese": "[Trustpilot/GB] easy to navigate, confirm selection and pay."
  },
  {
    "id": "TP-005",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "DE",
    "rating": "5",
    "sentiment": "正面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Love my P1S and the filaments :)",
    "chinese": "[Trustpilot/DE] Love my P1S and the filaments :)"
  },
  {
    "id": "TP-006",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "US",
    "rating": "5",
    "sentiment": "正面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Great system. Slicer is easy to use and easy to learn.",
    "chinese": "[Trustpilot/US] Great system. Slicer is easy to use and easy to learn."
  },
  {
    "id": "TP-007",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "NL",
    "rating": "3",
    "sentiment": "中性",
    "category": "物流配送",
    "issue_type": "物流商服务",
    "original": "why 2 deliveries, for 1 order? All was good. But why 2 delivery companies for 1 order? There were 6 spools in 1 order. 1 spool by DHL, the other 1 with PDP, all same day, other times.",
    "chinese": "[Trustpilot/NL] why 2 deliveries, for 1 order? All was good. But why 2 delivery companies for 1 ..."
  },
  {
    "id": "TP-008",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "US",
    "rating": "2",
    "sentiment": "负面",
    "category": "物流配送",
    "issue_type": "物流追踪",
    "original": "package tracking is poor. Package tracking is poor, never know where the package is. Please show the physical location (city-state)",
    "chinese": "[Trustpilot/US] package tracking is poor. Package tracking is poor, never know where the package..."
  },
  {
    "id": "TP-009",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "PT",
    "rating": "5",
    "sentiment": "正面",
    "category": "物流配送",
    "issue_type": "快速发货",
    "original": "The material arrived all extremely well packed and fast.",
    "chinese": "[Trustpilot/PT] The material arrived all extremely well packed and fast."
  },
  {
    "id": "TP-010",
    "platform": "Trustpilot",
    "date": "2026-04-07",
    "country": "ES",
    "rating": "5",
    "sentiment": "正面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Easy and quick approach to 3D printing world! Very clear information, best relation Quality-price.",
    "chinese": "[Trustpilot/ES] Easy and quick approach to 3D printing world! Very clear information, best relat..."
  },
  {
    "id": "TP-011",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "GB",
    "rating": "5",
    "sentiment": "正面",
    "category": "物流配送",
    "issue_type": "快速发货",
    "original": "Delivery was super fast, was well packaged and it was really easy to set up and get going with the printer. Would recommend this company to all.",
    "chinese": "[Trustpilot/GB] Delivery was super fast, was well packaged and it was really easy to set up and ..."
  },
  {
    "id": "TP-012",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "FR",
    "rating": "3",
    "sentiment": "中性",
    "category": "商城服务",
    "issue_type": "库存不足",
    "original": "Lack of stock, deliveries in several items at different dates. For one single order, I received 2 different deliveries on 2 consecutive days. I had to stay home 2 consecutive days to receive 2 items.",
    "chinese": "[Trustpilot/FR] Lack of stock, deliveries in several items at different dates. For one single or..."
  },
  {
    "id": "TP-013",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "ES",
    "rating": "5",
    "sentiment": "正面",
    "category": "其他",
    "issue_type": "待确认",
    "original": "Good packaging and quick",
    "chinese": "[Trustpilot/ES] Good packaging and quick"
  },
  {
    "id": "TP-014",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "NL",
    "rating": "3",
    "sentiment": "中性",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Sales tactics bad, printer excellent. The printer is excellent. But had I known about the X2D being just announced, I would have waited.",
    "chinese": "[Trustpilot/NL] Sales tactics bad, printer excellent. The printer is excellent. But had I known ..."
  },
  {
    "id": "TP-015",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "IT",
    "rating": "5",
    "sentiment": "正面",
    "category": "商城服务",
    "issue_type": "下单流程",
    "original": "Ordering on the website was very easy, and delivery was fast and perfectly tracked. The product I purchased, the BambuLab A1 Mini, was very easy to set up and prints at excellent quality.",
    "chinese": "[Trustpilot/IT] Ordering on the website was very easy, and delivery was fast and perfectly track..."
  },
  {
    "id": "TP-016",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "CZ",
    "rating": "5",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "客服满意",
    "original": "Customer service is perfect.",
    "chinese": "[Trustpilot/CZ] Customer service is perfect."
  },
  {
    "id": "TP-017",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "DE",
    "rating": "5",
    "sentiment": "正面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Great and Quick Delivery. Very good Printer (A1-Mini) and after some adjustments to the filament pretty solid and fast printing",
    "chinese": "[Trustpilot/DE] Great and Quick Delivery. Very good Printer (A1-Mini) and after some adjustments..."
  },
  {
    "id": "TP-018",
    "platform": "Trustpilot",
    "date": "2026-04-17",
    "country": "US",
    "rating": "2",
    "sentiment": "负面",
    "category": "物流配送",
    "issue_type": "发货延迟",
    "original": "Bambu Lab is slow getting the package to the shipper after they notify you that your package is shipped. Also Bambu Lab sometimes uses USPS and USPS is the absolute worst shipper there is.",
    "chinese": "[Trustpilot/US] Bambu Lab is slow getting the package to the shipper after they notify you that ..."
  },
  {
    "id": "TP-019",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "BR",
    "rating": "1",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "退款/退货",
    "original": "My order came missing 2 of 12 filaments. It has been a week I opened the ticket and no resolution. I told that I gave up the order and want to return everything, they don't reply or accept my return.",
    "chinese": "[Trustpilot/BR] My order came missing 2 of 12 filaments. It has been a week I opened the ticket ..."
  },
  {
    "id": "TP-020",
    "platform": "Trustpilot",
    "date": "2026-04-08",
    "country": "US",
    "rating": "4",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "客服满意",
    "original": "The support team has been very helpful when had a logistics problem with shipping now I'm hoping they can help with my ams problem",
    "chinese": "[Trustpilot/US] The support team has been very helpful when had a logistics problem with shippin..."
  },
  {
    "id": "TP-021",
    "platform": "Trustpilot",
    "date": "2026-04-13",
    "country": "IT",
    "rating": "5",
    "sentiment": "正面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Very well packed 3D printer and accessories. The shipment was fast. I will order more spare parts from them",
    "chinese": "[Trustpilot/IT] Very well packed 3D printer and accessories. The shipment was fast. I will order..."
  },
  {
    "id": "TP-022",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "AU",
    "rating": "4",
    "sentiment": "正面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "The ease of printing, what was hard to find was good instructions on how to use the slicer.",
    "chinese": "[Trustpilot/AU] The ease of printing, what was hard to find was good instructions on how to use ..."
  },
  {
    "id": "TP-023",
    "platform": "Trustpilot",
    "date": "2026-04-17",
    "country": "US",
    "rating": "3",
    "sentiment": "中性",
    "category": "物流配送",
    "issue_type": "物流商服务",
    "original": "Orders placed on Sunday or Monday are given to the carrier on Tuesday and 3-day delivery seems to be 4 or 5 days. Finding part numbers is a bit difficult, but I am learning.",
    "chinese": "[Trustpilot/US] Orders placed on Sunday or Monday are given to the carrier on Tuesday and 3-day ..."
  },
  {
    "id": "TP-024",
    "platform": "Trustpilot",
    "date": "2026-04-17",
    "country": "US",
    "rating": "3",
    "sentiment": "中性",
    "category": "其他",
    "issue_type": "待确认",
    "original": "Being a newbie, It was a tad bit confusing at first but kinda figured it out some. I am still very much lost on the methods used for uploading pictures of my finished models to your site.",
    "chinese": "[Trustpilot/US] Being a newbie, It was a tad bit confusing at first but kinda figured it out som..."
  },
  {
    "id": "TP-025",
    "platform": "Trustpilot",
    "date": "2026-04-18",
    "country": "US",
    "rating": "4",
    "sentiment": "正面",
    "category": "商城服务",
    "issue_type": "库存不足",
    "original": "I am having way too much fun with my P2S and AMS units. My only issue is lack of filament on the site. The ones I want to buy are constantly out of stock.",
    "chinese": "[Trustpilot/US] I am having way too much fun with my P2S and AMS units. My only issue is lack of..."
  },
  {
    "id": "TP-026",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "CA",
    "rating": "5",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "Amazing product and service",
    "chinese": "[Trustpilot/CA] Amazing product and service"
  },
  {
    "id": "TP-027",
    "platform": "Trustpilot",
    "date": "2026-04-09",
    "country": "AU",
    "rating": "5",
    "sentiment": "正面",
    "category": "商城服务",
    "issue_type": "支付问题",
    "original": "The ease of the ordering and payment process the speed of the delivery unpacking the product the quality of the presentation and the ease of the first use made it a very pleasurable experience.",
    "chinese": "[Trustpilot/AU] The ease of the ordering and payment process the speed of the delivery unpacking..."
  },
  {
    "id": "TP-028",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "US",
    "rating": "5",
    "sentiment": "正面",
    "category": "商城服务",
    "issue_type": "下单流程",
    "original": "Ordering was easy, price was good, and delivery was fast",
    "chinese": "[Trustpilot/US] Ordering was easy, price was good, and delivery was fast"
  },
  {
    "id": "TP-029",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "US",
    "rating": "3",
    "sentiment": "中性",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Company makes a fantastic 3d printer but their shipping time is terrible. They should offer express shipping if someone wants it instead of 3 to 9 day shipping.",
    "chinese": "[Trustpilot/US] Company makes a fantastic 3d printer but their shipping time is terrible. They s..."
  },
  {
    "id": "TP-030",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "CA",
    "rating": "3",
    "sentiment": "中性",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Great product, poor stock. Great product, but stock of filament is terrible.",
    "chinese": "[Trustpilot/CA] Great product, poor stock. Great product, but stock of filament is terrible."
  },
  {
    "id": "TP-031",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "AT",
    "rating": "5",
    "sentiment": "正面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Good reliable products. The shipping was fast. The software is perfect.",
    "chinese": "[Trustpilot/AT] Good reliable products. The shipping was fast. The software is perfect."
  },
  {
    "id": "TP-032",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "GB",
    "rating": "5",
    "sentiment": "正面",
    "category": "物流配送",
    "issue_type": "快速发货",
    "original": "Fast and efficient delivery thanks",
    "chinese": "[Trustpilot/GB] Fast and efficient delivery thanks"
  },
  {
    "id": "TP-033",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "US",
    "rating": "4",
    "sentiment": "正面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "The products are great, filaments are good quality only issue is that I got the p2s like 10 days before the x2d so yeah I wish y'all would do like an upgrade system.",
    "chinese": "[Trustpilot/US] The products are great, filaments are good quality only issue is that I got the ..."
  },
  {
    "id": "TP-034",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "US",
    "rating": "1",
    "sentiment": "负面",
    "category": "物流配送",
    "issue_type": "待确认",
    "original": "Shipping is ridiculous for filament. Ordered 17. 1 came by itself, 3 came after that then 18 days later the rest of the shipment arrived.",
    "chinese": "[Trustpilot/US] Shipping is ridiculous for filament. Ordered 17. 1 came by itself, 3 came after ..."
  },
  {
    "id": "TP-035",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "US",
    "rating": "5",
    "sentiment": "正面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "All of my purchases have been great. Product arrives in a timely manner and I've had no issues with filament quality.",
    "chinese": "[Trustpilot/US] All of my purchases have been great. Product arrives in a timely manner and I've..."
  },
  {
    "id": "TP-036",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "US",
    "rating": "5",
    "sentiment": "正面",
    "category": "商城服务",
    "issue_type": "下单流程",
    "original": "Very prompt! I ordered 2 hot ends for my H2C and received them in about 3 days. I really appreciate this company.",
    "chinese": "[Trustpilot/US] Very prompt! I ordered 2 hot ends for my H2C and received them in about 3 days. ..."
  },
  {
    "id": "TP-037",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "RO",
    "rating": "3",
    "sentiment": "中性",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "easy to use, needs to have stock for filaments and other parts",
    "chinese": "[Trustpilot/RO] easy to use, needs to have stock for filaments and other parts"
  },
  {
    "id": "TP-038",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "TH",
    "rating": "2",
    "sentiment": "负面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Open more shops and have more products in stock in Thailand. Now we have to wait for weeks for products and filaments, and Thai customs often add almost double the costs on import.",
    "chinese": "[Trustpilot/TH] Open more shops and have more products in stock in Thailand. Now we have to wait..."
  },
  {
    "id": "TP-039",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "IT",
    "rating": "1",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "退款/退货",
    "original": "A return policy bordering on a scam: you buy a printer at full price and 10 days later they release a new model. If you contact their customer support, they tell you that you can't refuse delivery.",
    "chinese": "[Trustpilot/IT] A return policy bordering on a scam: you buy a printer at full price and 10 days..."
  },
  {
    "id": "TP-040",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "GB",
    "rating": "5",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "Fast and efficient service",
    "chinese": "[Trustpilot/GB] Fast and efficient service"
  },
  {
    "id": "TP-041",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "US",
    "rating": "5",
    "sentiment": "正面",
    "category": "其他",
    "issue_type": "待确认",
    "original": "On time, great condition",
    "chinese": "[Trustpilot/US] On time, great condition"
  },
  {
    "id": "TP-042",
    "platform": "Trustpilot",
    "date": "2026-04-16",
    "country": "CA",
    "rating": "5",
    "sentiment": "正面",
    "category": "其他",
    "issue_type": "待确认",
    "original": "Always there for the correct answers",
    "chinese": "[Trustpilot/CA] Always there for the correct answers"
  },
  {
    "id": "TP-043",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "BE",
    "rating": "1",
    "sentiment": "负面",
    "category": "商城服务",
    "issue_type": "网站体验",
    "original": "I WAS blocked for no reason whatsoever from the website bambulab.com. So I am very disappointed. Fix it.",
    "chinese": "[Trustpilot/BE] I WAS blocked for no reason whatsoever from the website bambulab.com. So I am ve..."
  },
  {
    "id": "TP-044",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "US",
    "rating": "3",
    "sentiment": "中性",
    "category": "商城服务",
    "issue_type": "待确认",
    "original": "The only detractors are the add-on accessories. When viewing or selecting, they supersede the primary purchase. For example: I was buying a printer, and ended up buying a laser plate instead.",
    "chinese": "[Trustpilot/US] The only detractors are the add-on accessories. When viewing or selecting, they ..."
  },
  {
    "id": "TP-045",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "US",
    "rating": "5",
    "sentiment": "正面",
    "category": "物流配送",
    "issue_type": "待确认",
    "original": "No fuss, no issue, simple and shipped on time.",
    "chinese": "[Trustpilot/US] No fuss, no issue, simple and shipped on time."
  },
  {
    "id": "TP-046",
    "platform": "Trustpilot",
    "date": "2026-04-10",
    "country": "US",
    "rating": "5",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "客服满意",
    "original": "Easy to find the product and the associated links were very helpful!",
    "chinese": "[Trustpilot/US] Easy to find the product and the associated links were very helpful!"
  },
  {
    "id": "TP-047",
    "platform": "Trustpilot",
    "date": "2026-04-09",
    "country": "MY",
    "rating": "5",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "保修处理",
    "original": "AMAZING. I'm dealing with many companies but never have I experienced such a great and quick service like Bambu Lab. Not only are the products great, but the aftersales and warranty processing is a whole different level.",
    "chinese": "[Trustpilot/MY] AMAZING. I'm dealing with many companies but never have I experienced such a gre..."
  },
  {
    "id": "TP-048",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "US",
    "rating": "5",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "Great customer service and they made the situation better with a resolution that addressed all issues and concerns.",
    "chinese": "[Trustpilot/US] Great customer service and they made the situation better with a resolution that..."
  },
  {
    "id": "TP-049",
    "platform": "Trustpilot",
    "date": "2026-04-01",
    "country": "US",
    "rating": "3",
    "sentiment": "中性",
    "category": "物流配送",
    "issue_type": "待确认",
    "original": "The product is fantastic the delivery sucks.",
    "chinese": "[Trustpilot/US] The product is fantastic the delivery sucks."
  },
  {
    "id": "TP-050",
    "platform": "Trustpilot",
    "date": "2026-04-05",
    "country": "US",
    "rating": "1",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "响应慢",
    "original": "Bambu Lab has great products, but their customer service is non-existent. I've been waiting 3 weeks for a response to my warranty claim.",
    "chinese": "[Trustpilot/US] Bambu Lab has great products, but their customer service is non-existent. I've b..."
  },
  {
    "id": "TP-051",
    "platform": "Trustpilot",
    "date": "2026-04-03",
    "country": "DE",
    "rating": "5",
    "sentiment": "正面",
    "category": "物流配送",
    "issue_type": "快速发货",
    "original": "Fast shipping, great packaging. The printer arrived in perfect condition and was easy to set up.",
    "chinese": "[Trustpilot/DE] Fast shipping, great packaging. The printer arrived in perfect condition and was..."
  },
  {
    "id": "TP-052",
    "platform": "Trustpilot",
    "date": "2026-04-08",
    "country": "GB",
    "rating": "5",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "I had an issue with my order and the support team resolved it within 24 hours. Very impressed!",
    "chinese": "[Trustpilot/GB] I had an issue with my order and the support team resolved it within 24 hours. V..."
  },
  {
    "id": "TP-053",
    "platform": "Trustpilot",
    "date": "2026-04-12",
    "country": "FR",
    "rating": "5",
    "sentiment": "正面",
    "category": "商城服务",
    "issue_type": "下单流程",
    "original": "The website checkout process is smooth and the order confirmation was immediate. Delivery was on time.",
    "chinese": "[Trustpilot/FR] The website checkout process is smooth and the order confirmation was immediate...."
  },
  {
    "id": "TP-054",
    "platform": "Trustpilot",
    "date": "2026-04-06",
    "country": "AU",
    "rating": "1",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "退款/退货",
    "original": "Tried to get a refund for a defective item. Customer service kept asking for more photos and videos. After 2 weeks, still no resolution.",
    "chinese": "[Trustpilot/AU] Tried to get a refund for a defective item. Customer service kept asking for mor..."
  },
  {
    "id": "TP-055",
    "platform": "Trustpilot",
    "date": "2026-04-14",
    "country": "CA",
    "rating": "5",
    "sentiment": "正面",
    "category": "物流配送",
    "issue_type": "物流追踪",
    "original": "Great experience from order to delivery. The tracking system worked perfectly and the package arrived earlier than expected.",
    "chinese": "[Trustpilot/CA] Great experience from order to delivery. The tracking system worked perfectly an..."
  },
  {
    "id": "TP-056",
    "platform": "Trustpilot",
    "date": "2026-04-10",
    "country": "NL",
    "rating": "2",
    "sentiment": "负面",
    "category": "商城服务",
    "issue_type": "发票问题",
    "original": "The invoice they sent had wrong VAT information. Took 3 emails to get a corrected invoice. Not ideal for business purchases.",
    "chinese": "[Trustpilot/NL] The invoice they sent had wrong VAT information. Took 3 emails to get a correcte..."
  },
  {
    "id": "TP-057",
    "platform": "Trustpilot",
    "date": "2026-04-07",
    "country": "US",
    "rating": "2",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "My coupon code didn't work at checkout. Customer service said it was expired but the email said it was valid until end of April.",
    "chinese": "[Trustpilot/US] My coupon code didn't work at checkout. Customer service said it was expired but..."
  },
  {
    "id": "TP-058",
    "platform": "Trustpilot",
    "date": "2026-04-15",
    "country": "IT",
    "rating": "5",
    "sentiment": "正面",
    "category": "物流配送",
    "issue_type": "待确认",
    "original": "Ordered spare parts and they arrived in 5 days. No issues with the order process or delivery.",
    "chinese": "[Trustpilot/IT] Ordered spare parts and they arrived in 5 days. No issues with the order process..."
  },
  {
    "id": "TP-059",
    "platform": "Trustpilot",
    "date": "2026-04-09",
    "country": "ES",
    "rating": "2",
    "sentiment": "负面",
    "category": "商城服务",
    "issue_type": "支付问题",
    "original": "The payment process failed twice before going through. No error message, just a blank page. Eventually worked on the third try.",
    "chinese": "[Trustpilot/ES] The payment process failed twice before going through. No error message, just a ..."
  },
  {
    "id": "TP-060",
    "platform": "Trustpilot",
    "date": "2026-04-11",
    "country": "SE",
    "rating": "5",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "保修处理",
    "original": "Excellent after-sales support. When my printer had an issue, they sent a replacement part free of charge within a week.",
    "chinese": "[Trustpilot/SE] Excellent after-sales support. When my printer had an issue, they sent a replace..."
  },
  {
    "id": "RD-001",
    "platform": "Reddit",
    "date": "2026-04-20",
    "country": "",
    "rating": "3",
    "sentiment": "中性",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "Best solution is to physically go to a store to pick it up. Customer service is much better when you have a physical receipt and can walk back in.",
    "chinese": "[Reddit/r/BambuLab] Best solution is to physically go to a store to pick it up. Customer service is ..."
  },
  {
    "id": "RD-002",
    "platform": "Reddit",
    "date": "2026-04-20",
    "country": "",
    "rating": "3",
    "sentiment": "中性",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "In the UK, there are only e-retailers who ship to you and don't have a physical store. Bambu support has been hit or miss for me.",
    "chinese": "[Reddit/r/BambuLab] In the UK, there are only e-retailers who ship to you and don't have a physical ..."
  },
  {
    "id": "RD-003",
    "platform": "Reddit",
    "date": "2026-04-21",
    "country": "",
    "rating": "2",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "工单处理",
    "original": "I am sad to learn this after getting my printer and having issues. Customer service took 2 weeks to respond to my ticket.",
    "chinese": "[Reddit/r/BambuLab] I am sad to learn this after getting my printer and having issues. Customer serv..."
  },
  {
    "id": "RD-004",
    "platform": "Reddit",
    "date": "2026-04-15",
    "country": "",
    "rating": "1",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "Brand new A1 broken on purchase. Horrible customer service experience. They told me to contact the retailer instead of helping directly.",
    "chinese": "[Reddit/r/BambuLab] Brand new A1 broken on purchase. Horrible customer service experience. They told..."
  },
  {
    "id": "RD-005",
    "platform": "Reddit",
    "date": "2026-04-15",
    "country": "",
    "rating": "3",
    "sentiment": "中性",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "They are 100% correct. Take it back to the retailer. Customer service from Bambu is only for products bought directly from them.",
    "chinese": "[Reddit/r/BambuLab] They are 100% correct. Take it back to the retailer. Customer service from Bambu..."
  },
  {
    "id": "RD-006",
    "platform": "Reddit",
    "date": "2026-04-15",
    "country": "",
    "rating": "4",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "保修处理",
    "original": "DOAs happen from any brand. Assembly for that machine is a 10 minute job. Bambu support usually sends replacement parts quickly.",
    "chinese": "[Reddit/r/BambuLab] DOAs happen from any brand. Assembly for that machine is a 10 minute job. Bambu ..."
  },
  {
    "id": "RD-007",
    "platform": "Reddit",
    "date": "2026-04-12",
    "country": "",
    "rating": "1",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "保修处理",
    "original": "Bambu Lab denied warranty after a build plate crash. I've been trying to get support for 3 weeks and they keep closing my ticket.",
    "chinese": "[Reddit/r/BambuLab] Bambu Lab denied warranty after a build plate crash. I've been trying to get sup..."
  },
  {
    "id": "RD-008",
    "platform": "Reddit",
    "date": "2026-04-14",
    "country": "",
    "rating": "4",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "保修处理",
    "original": "Case update: Bambu Lab has now re-evaluated the case and approved the warranty replacement. Support eventually came through.",
    "chinese": "[Reddit/r/BambuLab] Case update: Bambu Lab has now re-evaluated the case and approved the warranty r..."
  },
  {
    "id": "RD-009",
    "platform": "Reddit",
    "date": "2026-04-12",
    "country": "",
    "rating": "2",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "保修处理",
    "original": "I read the whole thing. I completely understand your frustration with Bambu's warranty process. It took me 3 weeks too.",
    "chinese": "[Reddit/r/BambuLab] I read the whole thing. I completely understand your frustration with Bambu's wa..."
  },
  {
    "id": "RD-010",
    "platform": "Reddit",
    "date": "2026-04-11",
    "country": "",
    "rating": "4",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "保修处理",
    "original": "A1 Blob broke toolhead. Had my A1 less than 2 weeks. Support sent a replacement toolhead within 3 days, very impressed.",
    "chinese": "[Reddit/r/BambuLab] A1 Blob broke toolhead. Had my A1 less than 2 weeks. Support sent a replacement ..."
  },
  {
    "id": "RD-011",
    "platform": "Reddit",
    "date": "2026-04-11",
    "country": "",
    "rating": "3",
    "sentiment": "中性",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "Jeez. I just got an A1 and haven't opened it yet. This support experience is making me nervous.",
    "chinese": "[Reddit/r/BambuLab] Jeez. I just got an A1 and haven't opened it yet. This support experience is mak..."
  },
  {
    "id": "RD-012",
    "platform": "Reddit",
    "date": "2026-04-19",
    "country": "",
    "rating": "1",
    "sentiment": "负面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "My A1 board melted, the replacement printer Bambu sent then also had issues. Support has been going back and forth for months.",
    "chinese": "[Reddit/r/BambuLab] My A1 board melted, the replacement printer Bambu sent then also had issues. Sup..."
  },
  {
    "id": "RD-013",
    "platform": "Reddit",
    "date": "2026-04-19",
    "country": "",
    "rating": "2",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "保修处理",
    "original": "I've had mixed general support. They initially responded quickly but then went silent for 2 weeks on my warranty claim.",
    "chinese": "[Reddit/r/BambuLab] I've had mixed general support. They initially responded quickly but then went s..."
  },
  {
    "id": "RD-014",
    "platform": "Reddit",
    "date": "2026-04-19",
    "country": "",
    "rating": "1",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "保修处理",
    "original": "Bambu support is garbage. My A1 stopped heating the bed after 6 months and they refused warranty saying it was user damage.",
    "chinese": "[Reddit/r/BambuLab] Bambu support is garbage. My A1 stopped heating the bed after 6 months and they ..."
  },
  {
    "id": "RD-015",
    "platform": "Reddit",
    "date": "2026-04-19",
    "country": "",
    "rating": "5",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "Bambu Lab Support - I'm trying to get a better experience. Support is very good in both cases I needed them, resolved within 24 hours.",
    "chinese": "[Reddit/r/BambuLab] Bambu Lab Support - I'm trying to get a better experience. Support is very good ..."
  },
  {
    "id": "RD-016",
    "platform": "Reddit",
    "date": "2026-04-19",
    "country": "",
    "rating": "5",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "退款/退货",
    "original": "I never have had an issue with support, their return period is generous and the team is responsive.",
    "chinese": "[Reddit/r/BambuLab] I never have had an issue with support, their return period is generous and the ..."
  },
  {
    "id": "RD-017",
    "platform": "Reddit",
    "date": "2026-04-19",
    "country": "",
    "rating": "1",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "Terrible customer support. I started initially for a P2S combo issue - took 3 weeks and multiple follow-ups to get a resolution.",
    "chinese": "[Reddit/r/BambuLab] Terrible customer support. I started initially for a P2S combo issue - took 3 we..."
  },
  {
    "id": "RD-018",
    "platform": "Reddit",
    "date": "2026-04-11",
    "country": "",
    "rating": "4",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "保修处理",
    "original": "Right out of the box - Ordered a H2C. Showed up with a shattered nozzle. Asked for replacement, support responded in 24 hours.",
    "chinese": "[Reddit/r/BambuLab] Right out of the box - Ordered a H2C. Showed up with a shattered nozzle. Asked f..."
  },
  {
    "id": "RD-019",
    "platform": "Reddit",
    "date": "2026-04-11",
    "country": "",
    "rating": "3",
    "sentiment": "中性",
    "category": "客服体验",
    "issue_type": "响应慢",
    "original": "If you've already opened a ticket to return it, I suggest you wait. Bambu's return process takes about 5-7 business days.",
    "chinese": "[Reddit/r/BambuLab] If you've already opened a ticket to return it, I suggest you wait. Bambu's retu..."
  },
  {
    "id": "RD-020",
    "platform": "Reddit",
    "date": "2026-04-09",
    "country": "",
    "rating": "2",
    "sentiment": "负面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Yet another victim of BambuLab P2S. The problem with this hobby is that the machines are guaranteed to have issues eventually.",
    "chinese": "[Reddit/r/BambuLab] Yet another victim of BambuLab P2S. The problem with this hobby is that the mach..."
  },
  {
    "id": "RD-021",
    "platform": "Reddit",
    "date": "2026-04-09",
    "country": "",
    "rating": "3",
    "sentiment": "中性",
    "category": "客服体验",
    "issue_type": "退款/退货",
    "original": "This is why I always buy from a physical store if possible. Returns and warranty claims are so much easier in person.",
    "chinese": "[Reddit/r/BambuLab] This is why I always buy from a physical store if possible. Returns and warranty..."
  },
  {
    "id": "RD-022",
    "platform": "Reddit",
    "date": "2026-04-06",
    "country": "",
    "rating": "1",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "Bambu A1 dead after 2 months of support, multiple parts replaced. I had a similar issue - toolhead error after 6 months, support was slow.",
    "chinese": "[Reddit/r/BambuLab] Bambu A1 dead after 2 months of support, multiple parts replaced. I had a simila..."
  },
  {
    "id": "RD-023",
    "platform": "Reddit",
    "date": "2026-04-07",
    "country": "",
    "rating": "5",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "Bambu labs has some of the best customer service I've personally experienced. They replaced my entire hotend assembly no questions asked.",
    "chinese": "[Reddit/r/BambuLab] Bambu labs has some of the best customer service I've personally experienced. Th..."
  },
  {
    "id": "RD-024",
    "platform": "Reddit",
    "date": "2026-04-03",
    "country": "",
    "rating": "1",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "保修处理",
    "original": "Replacement P2S 3 months in and already have another support ticket open. The replacement unit had the same issue as the original.",
    "chinese": "[Reddit/r/BambuLab] Replacement P2S 3 months in and already have another support ticket open. The re..."
  },
  {
    "id": "RD-025",
    "platform": "Reddit",
    "date": "2026-04-02",
    "country": "",
    "rating": "1",
    "sentiment": "负面",
    "category": "物流配送",
    "issue_type": "待确认",
    "original": "Printers not delivered, no solution from support. Two printers ordered, neither arrived. Support keeps saying to wait.",
    "chinese": "[Reddit/r/BambuLab] Printers not delivered, no solution from support. Two printers ordered, neither ..."
  },
  {
    "id": "RD-026",
    "platform": "Reddit",
    "date": "2026-04-03",
    "country": "",
    "rating": "",
    "sentiment": "中性",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "Hi, we're truly sorry for the frustrating experience. We've escalated your case and will provide a resolution within 48 hours.",
    "chinese": "[Reddit/r/BambuLab] Hi, we're truly sorry for the frustrating experience. We've escalated your case ..."
  },
  {
    "id": "RD-027",
    "platform": "Reddit",
    "date": "2026-04-01",
    "country": "",
    "rating": "1",
    "sentiment": "负面",
    "category": "物流配送",
    "issue_type": "待确认",
    "original": "Four months of trying to get a refund. FedEx is so bad now - they just delivered to the wrong address and Bambu won't help.",
    "chinese": "[Reddit/r/BambuLab] Four months of trying to get a refund. FedEx is so bad now - they just delivered..."
  },
  {
    "id": "RD-028",
    "platform": "Reddit",
    "date": "2026-04-20",
    "country": "",
    "rating": "3",
    "sentiment": "中性",
    "category": "物流配送",
    "issue_type": "发货延迟",
    "original": "X2D Shipping to Spain from Germany via YunExpress. Ordered my X2D and it's being shipped via YunExpress which is very slow.",
    "chinese": "[Reddit/r/BambuLab] X2D Shipping to Spain from Germany via YunExpress. Ordered my X2D and it's being..."
  },
  {
    "id": "RD-029",
    "platform": "Reddit",
    "date": "2026-04-20",
    "country": "",
    "rating": "3",
    "sentiment": "中性",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "I had the same question! My order has been split between two carriers. The AMS came via DHL but the printer via YunExpress.",
    "chinese": "[Reddit/r/BambuLab] I had the same question! My order has been split between two carriers. The AMS c..."
  },
  {
    "id": "RD-030",
    "platform": "Reddit",
    "date": "2026-04-20",
    "country": "",
    "rating": "3",
    "sentiment": "中性",
    "category": "物流配送",
    "issue_type": "待确认",
    "original": "Mine got delivered via YunExpress, then ended up getting delivered by local post. Took 12 days total from Germany.",
    "chinese": "[Reddit/r/BambuLab] Mine got delivered via YunExpress, then ended up getting delivered by local post..."
  },
  {
    "id": "RD-031",
    "platform": "Reddit",
    "date": "2026-04-20",
    "country": "",
    "rating": "2",
    "sentiment": "负面",
    "category": "物流配送",
    "issue_type": "分批发货",
    "original": "Same, ordered from Spain. AMS HT comes from DHL, X2C comes from YunExpress. Split shipments are really frustrating.",
    "chinese": "[Reddit/r/BambuLab] Same, ordered from Spain. AMS HT comes from DHL, X2C comes from YunExpress. Spli..."
  },
  {
    "id": "RD-032",
    "platform": "Reddit",
    "date": "2026-04-14",
    "country": "",
    "rating": "1",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "响应慢",
    "original": "Efficient support... now that's a fairy tale. Been waiting 3 weeks for a response on my warranty claim for a failed heatbed.",
    "chinese": "[Reddit/r/BambuLab] Efficient support... now that's a fairy tale. Been waiting 3 weeks for a respons..."
  },
  {
    "id": "RD-033",
    "platform": "Reddit",
    "date": "2026-04-15",
    "country": "",
    "rating": "4",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "退款/退货",
    "original": "Is there any reason not to return a P2S I bought last week to get the X2D instead? The return process was smooth and quick.",
    "chinese": "[Reddit/r/BambuLab] Is there any reason not to return a P2S I bought last week to get the X2D instea..."
  },
  {
    "id": "RD-034",
    "platform": "Reddit",
    "date": "2026-04-15",
    "country": "",
    "rating": "5",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "退款/退货",
    "original": "Absolutely return it. I would definitely get the X2D. Bambu's return policy is 30 days no questions asked.",
    "chinese": "[Reddit/r/BambuLab] Absolutely return it. I would definitely get the X2D. Bambu's return policy is 3..."
  },
  {
    "id": "RD-035",
    "platform": "Reddit",
    "date": "2026-04-15",
    "country": "",
    "rating": "2",
    "sentiment": "负面",
    "category": "商城服务",
    "issue_type": "待确认",
    "original": "Downvotes incoming no doubt, but it's pretty garbage behavior from Bambu to announce a new model right after people bought the old one.",
    "chinese": "[Reddit/r/BambuLab] Downvotes incoming no doubt, but it's pretty garbage behavior from Bambu to anno..."
  },
  {
    "id": "RD-036",
    "platform": "Reddit",
    "date": "2026-04-03",
    "country": "",
    "rating": "4",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "P2S brand new with spaghetti and heatbed problems. Bambu lab support is easy to deal with and will have you try some things first.",
    "chinese": "[Reddit/r/BambuLab] P2S brand new with spaghetti and heatbed problems. Bambu lab support is easy to ..."
  },
  {
    "id": "RD-037",
    "platform": "Reddit",
    "date": "2026-04-03",
    "country": "",
    "rating": "4",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "保修处理",
    "original": "Treat it as a defective unit since it's brand new and not working. Contact support immediately and request a replacement.",
    "chinese": "[Reddit/r/BambuLab] Treat it as a defective unit since it's brand new and not working. Contact suppo..."
  },
  {
    "id": "RD-038",
    "platform": "Reddit",
    "date": "2026-04-03",
    "country": "",
    "rating": "2",
    "sentiment": "负面",
    "category": "客服体验",
    "issue_type": "待确认",
    "original": "I am having loads of spaghetti issues too. Support sent me a new extruder but the problem persists.",
    "chinese": "[Reddit/r/BambuLab] I am having loads of spaghetti issues too. Support sent me a new extruder but th..."
  },
  {
    "id": "RD-039",
    "platform": "Reddit",
    "date": "2026-04-21",
    "country": "",
    "rating": "2",
    "sentiment": "负面",
    "category": "产品体验",
    "issue_type": "待确认",
    "original": "Replacement Parts - I need a new filament sensor for my printer and the Bambu store has been out of stock for 3 weeks.",
    "chinese": "[Reddit/r/BambuLab] Replacement Parts - I need a new filament sensor for my printer and the Bambu st..."
  },
  {
    "id": "RD-040",
    "platform": "Reddit",
    "date": "2026-04-19",
    "country": "",
    "rating": "4",
    "sentiment": "正面",
    "category": "商城服务",
    "issue_type": "库存不足",
    "original": "I've bought from both Best Buy and Microcenter. Usually from Microcenter because returns are easier and they have better stock.",
    "chinese": "[Reddit/r/BambuLab] I've bought from both Best Buy and Microcenter. Usually from Microcenter because..."
  },
  {
    "id": "RD-041",
    "platform": "Reddit",
    "date": "2026-04-19",
    "country": "",
    "rating": "4",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "退款/退货",
    "original": "Best Buy or Microcenter, both are good. More people will have experience with in-store returns which is easier than online.",
    "chinese": "[Reddit/r/BambuLab] Best Buy or Microcenter, both are good. More people will have experience with in..."
  },
  {
    "id": "RD-042",
    "platform": "Reddit",
    "date": "2026-04-09",
    "country": "",
    "rating": "5",
    "sentiment": "正面",
    "category": "商城服务",
    "issue_type": "下单流程",
    "original": "There's a discount, 35% I think, if you buy with the printer. The website checkout process makes it easy to bundle accessories.",
    "chinese": "[Reddit/r/BambuLab] There's a discount, 35% I think, if you buy with the printer. The website checko..."
  },
  {
    "id": "RD-043",
    "platform": "Reddit",
    "date": "2026-04-09",
    "country": "",
    "rating": "4",
    "sentiment": "正面",
    "category": "商城服务",
    "issue_type": "下单流程",
    "original": "idk if you can buy refills with the 40% deal but if you can that's a great deal. The website ordering process is straightforward.",
    "chinese": "[Reddit/r/BambuLab] idk if you can buy refills with the 40% deal but if you can that's a great deal...."
  },
  {
    "id": "RD-044",
    "platform": "Reddit",
    "date": "2026-04-16",
    "country": "",
    "rating": "3",
    "sentiment": "中性",
    "category": "客服体验",
    "issue_type": "退款/退货",
    "original": "I got a P2S a few weeks ago and I am also having the buyers remorse now that X2D is announced. Return window closes in 2 days.",
    "chinese": "[Reddit/r/BambuLab] I got a P2S a few weeks ago and I am also having the buyers remorse now that X2D..."
  },
  {
    "id": "RD-045",
    "platform": "Reddit",
    "date": "2026-04-16",
    "country": "",
    "rating": "4",
    "sentiment": "正面",
    "category": "客服体验",
    "issue_type": "退款/退货",
    "original": "I don't think you need it, but if I was in the window to return I would. Bambu's 30-day return policy is very fair.",
    "chinese": "[Reddit/r/BambuLab] I don't think you need it, but if I was in the window to return I would. Bambu's..."
  }
];
