window.DATA_SURVEY_W14 = [
  {
    "id": 1,
    "week": "W14",
    "date": "2026-04-08",
    "csm": "#20260306-00870",
    "channel": "WEB",
    "agent": "可力鸥",
    "region": "US",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "You provide a great product with awesome service to back it up. The only improvement I could possibly suggest is, to be faster with the product. My AMS took 2 months and the replacement part took a month to receive. Overall, I am very pleased with my printer and AMS system. Everything else is perfect."
  },
  {
    "id": 2,
    "week": "W14",
    "date": "2026-04-07",
    "csm": "#20260330-00599",
    "channel": "WEB",
    "agent": "饼饼",
    "region": "CA",
    "issue_types": [
      "I have questions before placing an order",
      "I have questions before placing an order",
      "I have questions before placing an order"
    ],
    "issue_type_1": "I have questions before placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 3,
    "week": "W14",
    "date": "2026-04-07",
    "csm": "#20260330-00603",
    "channel": "WEB",
    "agent": "聂芳瓶",
    "region": "CA",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 4,
    "week": "W14",
    "date": "2026-04-07",
    "csm": "#20260401-01553",
    "channel": "WEB",
    "agent": "蜡笔",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 4.0,
    "feedback": ""
  },
  {
    "id": 5,
    "week": "W14",
    "date": "2026-04-06",
    "csm": "#20260318-00080",
    "channel": "邮件",
    "agent": "维他",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 2.0,
    "tags": "Order and Delivery",
    "nps": 2.0,
    "feedback": "Most of my feedback can be found in the ticket itself. Replies to the ticket were mechanical with some errors. Felt like AI responses. Your solution to the issue was to do the exact same thing that caused the issue in the first place. Replacement unit was shipped even though your response was negative to my conditions for shipping (ie I wanted signature required or held for pickup). No contact info for Carrier. Long response times, no ability to talk to Cust. Service directly. problem not elevat"
  },
  {
    "id": 6,
    "week": "W14",
    "date": "2026-04-06",
    "csm": "#20260331-01968",
    "channel": "邮件",
    "agent": "Cady",
    "region": "US",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 7,
    "week": "W14",
    "date": "2026-04-06",
    "csm": "#20260402-01560",
    "channel": "邮件",
    "agent": "Savannah",
    "region": "EU",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 8,
    "week": "W14",
    "date": "2026-04-06",
    "csm": "#20260320-00267",
    "channel": "邮件",
    "agent": "三鲜豆皮",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Bonjour, je souhaite à nouveau à faire l'éloge du professionnalisme et de la réactivité du service support bambulab, je le recommande tous les jours à toute personne qui rencontre des difficultés. Une très bonne expérience support !!"
  },
  {
    "id": 9,
    "week": "W14",
    "date": "2026-04-05",
    "csm": "#20260405-00547",
    "channel": "苹果",
    "agent": "鲫鱼饼",
    "region": "US",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Product Usage Experience/After-sales Service Policy/Customer Service",
    "nps": 1.0,
    "feedback": "I have had my printer for a little over one month and have had to tear it apart 7 times to fix things on it and feel like I got sold a bad printer!"
  },
  {
    "id": 10,
    "week": "W14",
    "date": "2026-04-05",
    "csm": "#20260329-00756",
    "channel": "WEB",
    "agent": "毛豆",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "A very welcome hassle free resolution. Very easy to work with."
  },
  {
    "id": 11,
    "week": "W14",
    "date": "2026-04-05",
    "csm": "#20260330-01137",
    "channel": "WEB",
    "agent": "柠檬爽",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 12,
    "week": "W14",
    "date": "2026-04-05",
    "csm": "#20260327-00510",
    "channel": "苹果",
    "agent": "舟鱼",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 13,
    "week": "W14",
    "date": "2026-04-05",
    "csm": "#20260326-00345",
    "channel": "苹果",
    "agent": "Kevin Stiehl",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 14,
    "week": "W14",
    "date": "2026-04-05",
    "csm": "#20260404-00388",
    "channel": "邮件",
    "agent": "蜡笔",
    "region": "EU",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery/After-sales Service Policy/Customer Service",
    "nps": 1.0,
    "feedback": "It is the last time I buy filament from the Bambu store, I will buy it from other platforms.\n\nI moved my entire setup from Creality to Bambu ecosystem because of similar frustrations with their customer service. Since switching, I invested in 2 P1S printers, 1 A1, accessories and filament.\n\nIt is disappointing you prefer to lose a loyal, high-value customer over a 16€ price adjustement. I'll ssess to remain with Bambu, but I need to see that you value yout customer more than a rigid sales policy"
  },
  {
    "id": 15,
    "week": "W14",
    "date": "2026-04-05",
    "csm": "#20260316-01457",
    "channel": "WEB",
    "agent": "火锅底料",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 16,
    "week": "W14",
    "date": "2026-04-05",
    "csm": "#20260402-00383",
    "channel": "邮件",
    "agent": "琰琰",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 17,
    "week": "W14",
    "date": "2026-04-05",
    "csm": "#20260401-01718",
    "channel": "安卓",
    "agent": "星云",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 18,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260327-01707",
    "channel": "邮件",
    "agent": "韩建琪",
    "region": "CA",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery/Customer Service",
    "nps": 3.0,
    "feedback": "Customer service is not good, it takes days to get an answer while they give automated responses. The printers are good but Customer service is seriously lacking."
  },
  {
    "id": 19,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260328-00002",
    "channel": "邮件",
    "agent": "昙花",
    "region": "EU",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Good shipping time and quick service"
  },
  {
    "id": 20,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260316-00679",
    "channel": "邮件",
    "agent": "洋桔梗",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 21,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260329-01196",
    "channel": "邮件",
    "agent": "舟鱼",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 4.0,
    "feedback": "Logistics needs to work on their tickets & not show them as \"closed\" when only a portion of the ticket is fulfilled.  Also, a single point to look for Updates & statuses relating to Shipping, it gets very confusing with ALL of the MANY Options!   Overall, they are doin a pretty good job!!!!!  :-)"
  },
  {
    "id": 22,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260328-01048",
    "channel": "邮件",
    "agent": "星云",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 4.0,
    "feedback": ""
  },
  {
    "id": 23,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260329-00151",
    "channel": "WEB",
    "agent": "柠七",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 24,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260314-00150",
    "channel": "邮件",
    "agent": "青篱竹",
    "region": "EU",
    "issue_types": [
      "I have questions before placing an order",
      "I have questions before placing an order",
      "I have questions before placing an order"
    ],
    "issue_type_1": "I have questions before placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 25,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260330-01986",
    "channel": "邮件",
    "agent": "琰琰",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "I got fast and very good support. Thank u"
  },
  {
    "id": 26,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260325-01705",
    "channel": "邮件",
    "agent": "豆沙",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 2.0,
    "tags": "Order and Delivery/After-sales Service Policy/Customer Service",
    "nps": 3.0,
    "feedback": "The printer seems good, but the support experience was disappointing. This basic installation issue took about 5 days to clarify. I received delayed replies, repeated template messages, and conflicting information between the documentation, support replies, and package contents. The final solution was to cut one PTFE tube to compensate for this inconsistency. Please improve response time, technical clarity, and documentation consistency."
  },
  {
    "id": 27,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260318-00279",
    "channel": "邮件",
    "agent": "柠七",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Dans ma région certains transporteur comme ups n'ont pas bonne réputation. Une amélioration est de laisser l'utilisateur choisir durant une commande son transporteur préféré de confiance."
  },
  {
    "id": 28,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260323-01580",
    "channel": "WEB",
    "agent": "独角兽",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 29,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260225-01846",
    "channel": "WEB",
    "agent": "赤霞珠",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 3.0,
    "tags": "Customer Service/After-sales Service Policy/Order and Delivery",
    "nps": 4.0,
    "feedback": "I did eventually get a new printer but the whole support process takes way to long which is disgraceful and that I only got 25 euro compensation, there should also be a phone number for quick and better support."
  },
  {
    "id": 30,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260325-00415",
    "channel": "邮件",
    "agent": "阮丰",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 31,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260401-01941",
    "channel": "邮件",
    "agent": "甜豌豆",
    "region": "EU",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 32,
    "week": "W14",
    "date": "2026-04-04",
    "csm": "#20260401-00139",
    "channel": "邮件",
    "agent": "香葱赤虾",
    "region": "EU",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Perfecto"
  },
  {
    "id": 33,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260329-00719",
    "channel": "苹果",
    "agent": "陈红",
    "region": "US",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 34,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260318-01705",
    "channel": "邮件",
    "agent": "候鸟Cici",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Best customer service ever !!"
  },
  {
    "id": 35,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260324-01617",
    "channel": "邮件",
    "agent": "Savannah",
    "region": "UK",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Your courier (Yodel) was the problem. Getting them to take better care of the parcels is a real challenge."
  },
  {
    "id": 36,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260321-00513",
    "channel": "WEB",
    "agent": "Jeffrey Port",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 3.0,
    "tags": "Customer Service",
    "nps": 4.0,
    "feedback": ""
  },
  {
    "id": 37,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260320-01263",
    "channel": "邮件",
    "agent": "缘壹",
    "region": "EU",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 38,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260310-00066",
    "channel": "邮件",
    "agent": "草莓大福",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Very professional ! I keep on folowwing Bambu Labs"
  },
  {
    "id": 39,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260321-00401",
    "channel": "邮件",
    "agent": "Wiley",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 40,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260401-01593",
    "channel": "邮件",
    "agent": "Maria Altamirano",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery",
    "nps": 1.0,
    "feedback": "I solved the issue myself, the support did nothing but put me on hold. Thanks for nothing."
  },
  {
    "id": 41,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260317-01961",
    "channel": "邮件",
    "agent": "赤霞珠",
    "region": "UK",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 2.0,
    "tags": "Order and Delivery/Customer Service",
    "nps": 2.0,
    "feedback": "It took a long time to resolve the issue, with no sense of urgency to make things right. Even after escalation it took a long while"
  },
  {
    "id": 42,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260331-02240",
    "channel": "安卓",
    "agent": "Livia",
    "region": "Others",
    "issue_types": [
      "I have questions before placing an order",
      "I have questions before placing an order",
      "I have questions before placing an order"
    ],
    "issue_type_1": "I have questions before placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 43,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260331-01496",
    "channel": "邮件",
    "agent": "Savannah",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 44,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260326-00445",
    "channel": "邮件",
    "agent": "柠檬爽",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 45,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260403-00735",
    "channel": "苹果",
    "agent": "柠檬爽",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 46,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260307-00002",
    "channel": "WEB",
    "agent": "昙花",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 47,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260326-00732",
    "channel": "邮件",
    "agent": "麻球",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "You really need a phone number so people can reach an actual person."
  },
  {
    "id": 48,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260327-01464",
    "channel": "邮件",
    "agent": "Kevin Stiehl",
    "region": "EU",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "You guys are the best. I think in this world full of average things you are an example that some things are great. Please keep being very customer care and humane service you already are."
  },
  {
    "id": 49,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260325-00978",
    "channel": "WEB",
    "agent": "麻球",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 4.0,
    "feedback": ""
  },
  {
    "id": 50,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260402-00107",
    "channel": "安卓",
    "agent": "花生米",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 51,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260331-00902",
    "channel": "邮件",
    "agent": "洋桔梗",
    "region": "CA",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery",
    "nps": 1.0,
    "feedback": "Your bot did nothing but acknowledge it received my support ticket then deleted it because it said one already existed for this issue. Tell me where my order is"
  },
  {
    "id": 52,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260327-01636",
    "channel": "邮件",
    "agent": "Cady",
    "region": "Other",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Предлагаю для пользователей из России сделать связь, к примеру, через почту. В связи с блокировками интернета"
  },
  {
    "id": 53,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260319-00944",
    "channel": "邮件",
    "agent": "米努特",
    "region": "EU",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery/Customer Service",
    "nps": 1.0,
    "feedback": "Ich bekomme meine bezahlte Ware nicht und erhalte keine Information. Ich werde diesen Fall demnächst meinem Anwalt übergeben und eine Klage erwägen.\n\nIch bitte um umgehende Bearbeitung meines falls."
  },
  {
    "id": 54,
    "week": "W14",
    "date": "2026-04-03",
    "csm": "#20260322-01246",
    "channel": "WEB",
    "agent": "甜豌豆",
    "region": "EU",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 55,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260315-01149",
    "channel": "邮件",
    "agent": "合欢",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "The team is great, respond fast, and resovled my issue. I recommend highly Bambu for tje ecosystem and customer service."
  },
  {
    "id": 56,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260401-00385",
    "channel": "邮件",
    "agent": "花盈",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 57,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260313-01277",
    "channel": "邮件",
    "agent": "缘壹",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 58,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260306-00494",
    "channel": "安卓",
    "agent": "毛豆",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 59,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260323-01354",
    "channel": "邮件",
    "agent": "Savannah",
    "region": "CA",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 4.0,
    "feedback": "could be quicker"
  },
  {
    "id": 60,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260318-01940",
    "channel": "邮件",
    "agent": "莎丽",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 61,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260312-01406",
    "channel": "邮件",
    "agent": "柠七",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 62,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260323-00533",
    "channel": "邮件",
    "agent": "Savannah",
    "region": "EU",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 63,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260327-01553",
    "channel": "邮件",
    "agent": "Kevin Stiehl",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 64,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260323-00048",
    "channel": "邮件",
    "agent": "珊迪",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 65,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260321-00487",
    "channel": "邮件",
    "agent": "草莓大福",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Great customer service is why I stay with a company. Thank you for showing why Bambu is a leader in the industry!"
  },
  {
    "id": 66,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260325-00698",
    "channel": "邮件",
    "agent": "洋桔梗",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Getting my missing Bambu Bus Cable was a great experience. The support process was smooth, and the team was responsive and helpful throughout. I’m very satisfied with how quickly the issue was resolved. It really gives me confidence in Bambu Labs, and I’m glad I chose them for my first 3D printer."
  },
  {
    "id": 67,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260328-00150",
    "channel": "邮件",
    "agent": "柠七",
    "region": "US",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 68,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260320-01619",
    "channel": "邮件",
    "agent": "合欢",
    "region": "US",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "I did appreciate the response time"
  },
  {
    "id": 69,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260320-00389",
    "channel": "安卓",
    "agent": "昙花",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 70,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260321-00784",
    "channel": "WEB",
    "agent": "杏仁可颂",
    "region": "US",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 71,
    "week": "W14",
    "date": "2026-04-02",
    "csm": "#20260331-00452",
    "channel": "邮件",
    "agent": "Mina",
    "region": "EU",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 72,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260327-01597",
    "channel": "WEB",
    "agent": "Deniz Sarikaya",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 73,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260328-00622",
    "channel": "邮件",
    "agent": "维他",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Customer Service",
    "nps": 1.0,
    "feedback": "You guys sent me the same information I had already tried in the wiki that was no help so I waited several days to get information that was no help at all now a week later the issue is still unresolved. So thanks for nothing. Bob"
  },
  {
    "id": 74,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260322-00728",
    "channel": "安卓",
    "agent": "Savannah",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 75,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260401-01614",
    "channel": "邮件",
    "agent": "Savannah",
    "region": "",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 76,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260327-01521",
    "channel": "邮件",
    "agent": "合欢",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 77,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260329-00449",
    "channel": "邮件",
    "agent": "花螺",
    "region": "UK",
    "issue_types": [
      "I have questions before placing an order",
      "I have questions before placing an order",
      "I have questions before placing an order"
    ],
    "issue_type_1": "I have questions before placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "The agent fully understood my problem and dealt with it."
  },
  {
    "id": 78,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260331-02125",
    "channel": "邮件",
    "agent": "洋桔梗",
    "region": "",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 3.0,
    "tags": "After-sales Service Policy",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 79,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260202-01787",
    "channel": "邮件",
    "agent": "铭月",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 80,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260331-01720",
    "channel": "邮件",
    "agent": "花螺",
    "region": "Others",
    "issue_types": [
      "I have questions before placing an order",
      "I have questions before placing an order",
      "I have questions before placing an order"
    ],
    "issue_type_1": "I have questions before placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 81,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260311-01666",
    "channel": "WEB",
    "agent": "布朗",
    "region": "EU",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 82,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260324-00038",
    "channel": "邮件",
    "agent": "珊迪",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 83,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260331-01741",
    "channel": "邮件",
    "agent": "Savannah",
    "region": "",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Customer Service",
    "nps": 1.0,
    "feedback": "Fix you MFA"
  },
  {
    "id": 84,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260311-01363",
    "channel": "邮件",
    "agent": "三鲜豆皮",
    "region": "UK",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 85,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260331-01486",
    "channel": "邮件",
    "agent": "花螺",
    "region": "EU",
    "issue_types": [
      "I have questions before placing an order",
      "I have questions before placing an order",
      "I have questions before placing an order"
    ],
    "issue_type_1": "I have questions before placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 86,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260328-00003",
    "channel": "邮件",
    "agent": "星云",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "The update of your website regarding product availability is causing confusion about deliveries. At the time of my order, all products were listed as available, but they were only shipped two weeks later due to a stock shortage."
  },
  {
    "id": 87,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260326-01290",
    "channel": "邮件",
    "agent": "Jeffrey Port",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 2.0,
    "tags": "Customer Service/Others",
    "nps": 4.0,
    "feedback": "After creating my order, he immediately contacted the department with a request to change the ordered item. It was a hardened nozzle orig bambulab 0.6 and I wanted to exchange it for 0.4. I admitted my mistake and asked for a replacement of one piece.\nI myself work in a company where there is no problem in the order (if the price is the same) to make a change and be accommodating to the customer. This does not apply to you."
  },
  {
    "id": 88,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260331-01271",
    "channel": "苹果",
    "agent": "刘思瑜",
    "region": "UK",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 4.0,
    "feedback": "Speed"
  },
  {
    "id": 89,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260324-01024",
    "channel": "苹果",
    "agent": "莳雨",
    "region": "EU",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 4.0,
    "feedback": ""
  },
  {
    "id": 90,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260307-01265",
    "channel": "安卓",
    "agent": "赤霞珠",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 3.0,
    "tags": "Customer Service/After-sales Service Policy/Product Usage Experience/Order and Delivery",
    "nps": 4.0,
    "feedback": "Next time I mite get better one"
  },
  {
    "id": 91,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260220-01056",
    "channel": "邮件",
    "agent": "豆沙",
    "region": "US",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "The fact that you are patient and work to ensure whatever the issue is resolved is great.  I’ve been trying to buy additional items that are continually out of stock but I won’t give up cause I’m totally satisfied with your product, Thankyou"
  },
  {
    "id": 92,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260401-00299",
    "channel": "邮件",
    "agent": "蜡笔",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 93,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260327-01477",
    "channel": "邮件",
    "agent": "花螺",
    "region": "EU",
    "issue_types": [
      "I have questions before placing an order",
      "I have questions before placing an order",
      "I have questions before placing an order"
    ],
    "issue_type_1": "I have questions before placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 4.0,
    "feedback": ""
  },
  {
    "id": 94,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260329-00036",
    "channel": "邮件",
    "agent": "柠七",
    "region": "US",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Customer Service",
    "nps": 1.0,
    "feedback": "Good customer service is not that hard. We don't ask much, just that you fix things when some of your products er defective. You only have to abide by common EU law, that would be enough for a satisfied customer. But apparently you are not capable of doing that."
  },
  {
    "id": 95,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260326-02041",
    "channel": "WEB",
    "agent": "三鲜豆皮",
    "region": "CA",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 96,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260303-01675",
    "channel": "邮件",
    "agent": "星云",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 97,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260303-01150",
    "channel": "邮件",
    "agent": "铭月",
    "region": "AU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 98,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260211-01812",
    "channel": "邮件",
    "agent": "松雀鹰",
    "region": "Others",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Goog service"
  },
  {
    "id": 99,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260329-00102",
    "channel": "邮件",
    "agent": "鹤望兰",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "So far, my experience with Bambu Labs has been fantastic!"
  },
  {
    "id": 100,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260314-00717",
    "channel": "邮件",
    "agent": "薯角",
    "region": "CA",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 4.0,
    "feedback": "I have had a lot of issues with any UPS package you send out. I realize this isn't your fault but it would be great if I could choose to pay a higher shipping price so that you could make sure no packages go through UPS as a shipping service."
  },
  {
    "id": 101,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260325-01400",
    "channel": "邮件",
    "agent": "斯嘉丽",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 102,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260311-00883",
    "channel": "邮件",
    "agent": "赤霞珠",
    "region": "AU",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery/After-sales Service Policy/Customer Service",
    "nps": 1.0,
    "feedback": ""
  },
  {
    "id": 103,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260322-00285",
    "channel": "邮件",
    "agent": "薯角",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery/Customer Service",
    "nps": 3.0,
    "feedback": ""
  },
  {
    "id": 104,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260307-00165",
    "channel": "安卓",
    "agent": "独角兽",
    "region": "EU",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 105,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260327-00375",
    "channel": "邮件",
    "agent": "豆沙",
    "region": "US",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Others",
    "nps": 1.0,
    "feedback": "It simply does not work, We have been doing a number of the things you have suggested but as ofnow it simply does not work"
  },
  {
    "id": 106,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260326-02042",
    "channel": "邮件",
    "agent": "三鲜豆皮",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 107,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260319-01067",
    "channel": "邮件",
    "agent": "三鲜豆皮",
    "region": "US",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 2.0,
    "tags": "Order and Delivery/Customer Service",
    "nps": 2.0,
    "feedback": "I have placed two filament orders with Bambu, and I have had the same experience both times. The shipper marked the package as delivered, but that was not true. Customer service told me to check around my neighborhood (wrong answer). It's the shipper's responsibility to deliver the package to the correct location. My last order arrived 3 days after the shipper said it was delivered. No update or notification was given. Based on my experience, YunExpress is probably costing you a lot of money."
  },
  {
    "id": 108,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260327-01261",
    "channel": "邮件",
    "agent": "Kevin Stiehl",
    "region": "EU",
    "issue_types": [
      "I have questions before placing an order",
      "I have questions before placing an order",
      "I have questions before placing an order"
    ],
    "issue_type_1": "I have questions before placing an order",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Customer Service",
    "nps": 1.0,
    "feedback": "My address is not correct !!! I can't buy until It's correct"
  },
  {
    "id": 109,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260320-01414",
    "channel": "邮件",
    "agent": "舟鱼",
    "region": "UK",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 110,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260328-00633",
    "channel": "邮件",
    "agent": "柠檬爽",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 2.0,
    "tags": "After-sales Service Policy",
    "nps": 2.0,
    "feedback": "The company should stand behind all parts of its products.  Tools provided to maintain the product should be warrantied the same as the main unit.  Having a tool break as soon as I use it for the first time, and then being told too bad, is not acceptable.  Then telling me what tool I can go buy to replace it when I'm asking about supporting my new purchase is even worse.  You need to do better than that."
  },
  {
    "id": 111,
    "week": "W14",
    "date": "2026-04-01",
    "csm": "#20260320-00700",
    "channel": "邮件",
    "agent": "苦瓜",
    "region": "EU",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "After-sales Service Policy/Customer Service",
    "nps": 4.0,
    "feedback": "He tenido que resolver yo el problema perdiendo horas de trabajo esperando la solucion mas rapida que nunca llego, si desde un principio se me brinda la opcion de reenviar el producto dañado a servicio técnico se hubiera reparado o reemplazado con mayor brevedad pero he tenido que perder horas de trabajo, impresion entre otras cosas para solucionar yo mismo el problema, hagan un cambio en su politica de servicio posventa y solucionen los problemas o fallos de fabrica.\nGracias un cordial saludo."
  },
  {
    "id": 112,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260326-00251",
    "channel": "邮件",
    "agent": "合欢",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 113,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260326-00235",
    "channel": "邮件",
    "agent": "火锅底料",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 2.0,
    "tags": "Customer Service",
    "nps": 5.0,
    "feedback": "The client service doesn’t really understand what I ask. I think they dont really read messages…"
  },
  {
    "id": 114,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260327-01877",
    "channel": "邮件",
    "agent": "缘壹",
    "region": "EU",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "After-sales Service Policy/Customer Service",
    "nps": 1.0,
    "feedback": "Disappointed."
  },
  {
    "id": 115,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260327-00226",
    "channel": "邮件",
    "agent": "麻球",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Customer Service",
    "nps": 3.0,
    "feedback": "I just wanted 4 screws. How hard is it to send them or just send a link and I could have bought them. The package in all the other printers from the class I took had a baggy clearly marked A1 stiffiner screws. Why would it take me having to provide a picture of the parts I recieved (mind you the printer is setup already with cable chains and other misc prints on it that would clearly not be parts received in the box) and the box label to help you figure that out."
  },
  {
    "id": 116,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260313-00921",
    "channel": "邮件",
    "agent": "Savannah",
    "region": "US",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Ticket was initially closed before issue was resolved. When I responded with the right info I got replacement rolls pretty quickly."
  },
  {
    "id": 117,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260327-01239",
    "channel": "邮件",
    "agent": "斯嘉丽",
    "region": "UK",
    "issue_types": [
      "I have questions before placing an order",
      "I have questions before placing an order",
      "I have questions before placing an order"
    ],
    "issue_type_1": "I have questions before placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "As a new customer I was wondering apart from the news letter £10 for singing up discount no other discount was available. \nI was told that discounts were not available. \nPerhaps some kind of gesture could be available for new customers who purchase your goods just as I have."
  },
  {
    "id": 118,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260326-01395",
    "channel": "邮件",
    "agent": "莳雨",
    "region": "EU",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 119,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260325-01757",
    "channel": "邮件",
    "agent": "柠檬爽",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "I contacted bambu because the printer is amazing but had some questions on the voc risks and addl filtration systems that might be available for my h2s. While none are available or can be recommended due to warranty this may be an area of opportunity for bambu to sell add on filtration for people that cannot vent outside."
  },
  {
    "id": 120,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260328-00274",
    "channel": "邮件",
    "agent": "缘壹",
    "region": "US",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery/Customer Service",
    "nps": 3.0,
    "feedback": "I still haven’t received my order.  I ordered Feb 5 - I will not order from you again. I’m considering challenging the charge with my credit card. Not a good experience - I have received 3 rolls still waiting on 3.  Have received no updated tracking."
  },
  {
    "id": 121,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260331-00200",
    "channel": "邮件",
    "agent": "菜盒",
    "region": "",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery",
    "nps": 2.0,
    "feedback": "fail in system : invoice address and a delivery address to serve different purposes. Leading to lost orders!!\nIncompetent delivery service!"
  },
  {
    "id": 122,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260330-01755",
    "channel": "邮件",
    "agent": "琰琰",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Perfect"
  },
  {
    "id": 123,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260320-01208",
    "channel": "邮件",
    "agent": "缘壹",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 124,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260328-00818",
    "channel": "邮件",
    "agent": "莳雨",
    "region": "",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 4.0,
    "feedback": ""
  },
  {
    "id": 125,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260319-00120",
    "channel": "邮件",
    "agent": "Savannah",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 126,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260327-01645",
    "channel": "邮件",
    "agent": "维他",
    "region": "EU",
    "issue_types": [
      "I have questions before placing an order",
      "I have questions before placing an order",
      "I have questions before placing an order"
    ],
    "issue_type_1": "I have questions before placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 127,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260313-00354",
    "channel": "WEB",
    "agent": "柠七",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 128,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260313-00407",
    "channel": "邮件",
    "agent": "火锅底料",
    "region": "UK",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 129,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260312-01561",
    "channel": "WEB",
    "agent": "Jeffrey Port",
    "region": "EU",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 130,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260304-01435",
    "channel": "邮件",
    "agent": "星云",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 131,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260306-01171",
    "channel": "WEB",
    "agent": "独角兽",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Thank you for listening to me and for solving my problem."
  },
  {
    "id": 132,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260330-01479",
    "channel": "邮件",
    "agent": "洋桔梗",
    "region": "UK",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "After-sales Service Policy/Customer Service",
    "nps": 1.0,
    "feedback": "Absolutely useless. If you didn't exist the solution would have been identical. Why do you even have customer service when you DONT LISTEN OR REPLY TO WHAT IS SAID. \n\nabsolutely pathetic"
  },
  {
    "id": 133,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260328-00090",
    "channel": "邮件",
    "agent": "缘壹",
    "region": "EU",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 134,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260331-01103",
    "channel": "邮件",
    "agent": "Savannah",
    "region": "",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Communication was on point! Representative was very friendly and professional. Great experience!"
  },
  {
    "id": 135,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260327-00256",
    "channel": "邮件",
    "agent": "火锅底料",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Overall, I am very happy with your service. I did have some difficulty tracking my orders when they read as out for delivery or still in transit after a lengthy period of time. Nevertheless, once I figured out how to contact you and explain my issue to you, I immediately got a satisfactory response and within a few days, my issues were solved. Therefore, I am very happy with your service. Thank you."
  },
  {
    "id": 136,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260327-01539",
    "channel": "邮件",
    "agent": "合欢",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 3.0,
    "tags": "Customer Service",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 137,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260326-00446",
    "channel": "苹果",
    "agent": "火锅底料",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "From the very first reply to the reshipping resolution — everything was handled with care, speed, and a genuinely human touch. You made the whole process stress-free, and that’s not something I take for granted.\nKudos to the whole team. You’re doing an amazing job and it really shows. Keep it up!"
  },
  {
    "id": 138,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260328-00898",
    "channel": "邮件",
    "agent": "昙花",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery",
    "nps": 4.0,
    "feedback": "We like the products and we like the innovation, but I had difficulty placing my order and because of this it is being sent as five separate orders to a freight forwarding company and is going to cost a lot of extra money. \nWe are using these machines to help disabled veterans, and the extra money we spent is only taking away from them.\nI would've liked to have spoken to a real person."
  },
  {
    "id": 139,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260327-00142",
    "channel": "邮件",
    "agent": "合欢",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery",
    "nps": 3.0,
    "feedback": "I recieved no real reply. The site says 3 to 10 day delivery. It didn't even ship for 14 days and still has not arrived. Complete dissatisfaction with the order so far."
  },
  {
    "id": 140,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260327-01724",
    "channel": "邮件",
    "agent": "斯嘉丽",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 2.0,
    "tags": "Order and Delivery/Customer Service",
    "nps": 4.0,
    "feedback": "My issue was to address an ordering issue while it was still in a \"processing state\". my only option to contact anyone was through a ticket and it took far too long and my order shipped by the time they replied. so now I incur an additional shipping charge for another order for the parts I needed in the first place."
  },
  {
    "id": 141,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260325-00892",
    "channel": "安卓",
    "agent": "香葱赤虾",
    "region": "CA",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 142,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260330-00566",
    "channel": "邮件",
    "agent": "维他",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 143,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260316-01366",
    "channel": "安卓",
    "agent": "柴郡猫",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 3.0,
    "tags": "Order and Delivery",
    "nps": 4.0,
    "feedback": "Choose a different parcel partner"
  },
  {
    "id": 144,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260320-01094",
    "channel": "邮件",
    "agent": "琰琰",
    "region": "US",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 3.0,
    "feedback": "Your packing leaves a LOT to desire (except for printer and ams's) while returns are requested to be securely packed.  But CS did not understand my comment and pictures on it at all."
  },
  {
    "id": 145,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260311-00057",
    "channel": "邮件",
    "agent": "苦瓜",
    "region": "US",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "After that great customer service I just bought another A1. Thank you"
  },
  {
    "id": 146,
    "week": "W14",
    "date": "2026-03-31",
    "csm": "#20260324-01677",
    "channel": "邮件",
    "agent": "豆沙",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 2.0,
    "tags": "Customer Service",
    "nps": 3.0,
    "feedback": "Although I know that the customer service representative was doing the best that they could to help me, I think it is disgustingly inefficient, and frustrating that I have to request support online, wait 1-2 days for a response and not be able to speak to anyone over the phone for faster support. It’s also disgusting that my printer only worked for 9 months!"
  },
  {
    "id": 147,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260326-01780",
    "channel": "邮件",
    "agent": "青篱竹",
    "region": "US",
    "issue_types": [
      "I have questions before placing an order",
      "I have questions before placing an order",
      "I have questions before placing an order"
    ],
    "issue_type_1": "I have questions before placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 4.0,
    "feedback": "I submitted a ticket to get ordering assistance since there isn't a phone option.  The response was helpful, however my only options were to purchase direct to be tax exempt or contact a dealer and pay tax.  I'm in OKlahoma and there are NO dealers here.  So I did apply to be tax exempt however I still have no idea what to order.  So that is my reason for unresolved."
  },
  {
    "id": 148,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260318-01874",
    "channel": "邮件",
    "agent": "蜡笔",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery",
    "nps": 1.0,
    "feedback": "Never delivered product ordered"
  },
  {
    "id": 149,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260327-00066",
    "channel": "WEB",
    "agent": "柠檬爽",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "I can think of nothing, your service is second to none!"
  },
  {
    "id": 150,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260323-00279",
    "channel": "邮件",
    "agent": "花盈",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "El producto es excelente, y sus máquinas estupendas. Igual se podría mejorar la gestión de las facturas, porque es cierto que yo tengo dos usuarios y a veces los puedo confundir, la incidencia que tuve no salía el pedido en la página web en ninguno de los dos usuarios, es posible que hubiese algún problema informático. Otra posibilidad es que enviaran directamente la factura al correo electrónico del usuario .. Un saludo."
  },
  {
    "id": 151,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260303-01814",
    "channel": "邮件",
    "agent": "菜盒",
    "region": "UK",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 2.0,
    "tags": "After-sales Service Policy/Customer Service",
    "nps": 3.0,
    "feedback": "Your courier lost my package. You made me wait a month while you carried out multiple investigations. You made the customer who paid, wait weeks with no product while you investigated over and over.\n\nI spent a lot of money with you and had to wait weeks because of your mistakes. This is not good customer service, and I didn't get a decent apology.\n\nIf it wasn't for the fact that you make the best printers on the planet, I'd go elsewhere! :)"
  },
  {
    "id": 152,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260126-00258",
    "channel": "邮件",
    "agent": "赤霞珠",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 153,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260305-00860",
    "channel": "邮件",
    "agent": "菜盒",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Customer Service",
    "nps": 1.0,
    "feedback": "1. Hire people who can speak english without an accent. Cannot f%#king understand what the hell there saying. 2. Put you on hold multiple times, had to hang up out of frustration. 3. They considered matter resolved, but did not do a f#@king thing! 4. Make it easier to navigate the website to contact a REAL PERSON, don't bury it in with other unrelated options."
  },
  {
    "id": 154,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260330-01227",
    "channel": "邮件",
    "agent": "",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 4.0,
    "feedback": ""
  },
  {
    "id": 155,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260327-00188",
    "channel": "邮件",
    "agent": "款冬",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Quick response, great service overall, happy customer :)"
  },
  {
    "id": 156,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260324-01787",
    "channel": "邮件",
    "agent": "毛豆",
    "region": "EU",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 157,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260325-01668",
    "channel": "邮件",
    "agent": "莎丽",
    "region": "EU",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 3.0,
    "tags": "Customer Service",
    "nps": 4.0,
    "feedback": "I believe there was a help to solve my problem with the carrier but in a way they were not so fast in the answers."
  },
  {
    "id": 158,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260303-01325",
    "channel": "WEB",
    "agent": "柠檬爽",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 159,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260326-01884",
    "channel": "邮件",
    "agent": "缘壹",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 160,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260309-00942",
    "channel": "WEB",
    "agent": "布朗",
    "region": "Others",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "你們做得非常好 也許可以考慮 留點活路給其他競爭對手"
  },
  {
    "id": 161,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260329-00880",
    "channel": "邮件",
    "agent": "柚皮糖",
    "region": "EU",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Customer Service",
    "nps": 1.0,
    "feedback": "i sent twice picture of the broken part and just automatic responses. very bad customer service. selling is one thing, taking care of customer the other one which will influence the next buy"
  },
  {
    "id": 162,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260326-01582",
    "channel": "邮件",
    "agent": "花盈",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 163,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260312-01764",
    "channel": "邮件",
    "agent": "柴郡猫",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "On top for the customer services"
  },
  {
    "id": 164,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260323-01525",
    "channel": "安卓",
    "agent": "洋桔梗",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Hanno risolto il mio problema in modo esemplare e molto veloce ,grazie ."
  },
  {
    "id": 165,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260321-01382",
    "channel": "苹果",
    "agent": "毛豆",
    "region": "US",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": "Service was prompt and extremely helpful. Thank you again!"
  },
  {
    "id": 166,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260324-00877",
    "channel": "邮件",
    "agent": "维他",
    "region": "US",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 4.0,
    "tags": "",
    "nps": 4.0,
    "feedback": "I think that customer service did what was right according to the warranty policy. They were very kind. Unfortunately, I have had multiple hotend units break almost instantly, and that makes it challenging to purchase replacements knowing that I may be throwing money away."
  },
  {
    "id": 167,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260325-01931",
    "channel": "邮件",
    "agent": "缘壹",
    "region": "US",
    "issue_types": [],
    "issue_type_1": "",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Order and Delivery/After-sales Service Policy",
    "nps": 1.0,
    "feedback": "Unacceptable."
  },
  {
    "id": 168,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260327-01207",
    "channel": "邮件",
    "agent": "Winter",
    "region": "KR",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  },
  {
    "id": 169,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260327-00414",
    "channel": "邮件",
    "agent": "火锅底料",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 4.0,
    "feedback": ""
  },
  {
    "id": 170,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260317-00369",
    "channel": "邮件",
    "agent": "冰竹May",
    "region": "US",
    "issue_types": [
      "Complaints and Suggestions",
      "Complaints and Suggestions",
      "Complaints and Suggestions"
    ],
    "issue_type_1": "Complaints and Suggestions",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Customer Service",
    "nps": 1.0,
    "feedback": "You need to update your return shipping prices to explicitly state how much you'll be charged for each printer. It says nothing about a contract pricing with fedex, only about weight. I was NOT charged by weight, I was charged the next higher weight because it's negotiated. It's a scam you're running"
  },
  {
    "id": 171,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260320-00231",
    "channel": "邮件",
    "agent": "饼饼",
    "region": "US",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 1.0,
    "tags": "Customer Service",
    "nps": 1.0,
    "feedback": "Improve your customer service! Consider all parts of a request when denying it!"
  },
  {
    "id": 172,
    "week": "W14",
    "date": "2026-03-30",
    "csm": "#20260322-00828",
    "channel": "安卓",
    "agent": "星云",
    "region": "EU",
    "issue_types": [
      "I need help after placing an order",
      "I need help after placing an order",
      "I need help after placing an order"
    ],
    "issue_type_1": "I need help after placing an order",
    "resolved": true,
    "satisfaction": 5.0,
    "tags": "",
    "nps": 5.0,
    "feedback": ""
  }
];
